### ISSUE TITLE
Crash on drag/drop

### ISSUE THREAD

**Issue by regenman** [riverwm/river#548]
`(gdb) bt full
#0  0x00007f1d5f8c334c in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f1d5f8764b8 in raise () at /lib64/libc.so.6
#2  0x00007f1d5f860534 in abort () at /lib64/libc.so.6
#3  0x00000000002183d6 in std.os.abort () at /usr/lib/zig/std/os.zig:442
#4  0x0000000000218240 in std.debug.panicImpl (trace=<optimized out>, first_trace_addr=..., msg=...)
    at /usr/lib/zig/std/debug.zig:328
#5  0x0000000000216e86 in std.builtin.default_panicPython Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x6
 (msg=#6  0x0000000000250ec0 in .wayland.wayland_server_core.Link.remove
    (link=<optimized out>) at /home/jens/aur/river/src/river-0.1.3/zig-cache/zig-wayland/wayland_server_core.zig:491
        drag_icon = <optimized out>
        it = <optimized out>
        node = <optimized out>
#7  DragIcon.handleUnmap (listener=<optimized out>, _=<optimized out>) at DragIcon.zig:79
        drag_icon = <optimized out>
        it = <optimized out>
        node = <optimized out>
#8  .wayland.wayland_server_core.struct:490:17.wrapper (listener=<optimized out>, data=<optimized out>)
    at /home/jens/aur/river/src/river-0.1.3/zig-cache/zig-wayland/wayland_server_core.zig:492
#9  0x00007f1d5fac88fe in wlr_signal_emit_safe (signal=<optimized out>, data=0x1bdcfe0) at ../wlroots-0.15.1/util/signal.c:29
        pos = 0x1e28758
        l = 0x1e28758
        cursor = {link = {prev = 0x1e28758, next = 0x7ffe9473f980}, notify = 0x7f1d5fac5f10 <handle_noop>}
        end = {link = {prev = 0x7ffe9473f9a0, next = 0x1bdd008}, notify = 0x7f1d5fac5f10 <handle_noop>}
#10 0x00007f1d5fa944b6 in drag_icon_set_mapped (mapped=<optimized out>, icon=0x1bdcfe0)
    at ../wlroots-0.15.1/types/data_device/wlr_drag.c:114
#11 drag_icon_set_mapped (mapped=false, icon=0x1bdcfe0) at ../wlroots-0.15.1/types/data_device/wlr_drag.c:109
#12 drag_icon_destroy (icon=0x1bdcfe0) at ../wlroots-0.15.1/types/data_device/wlr_drag.c:365
#13 drag_icon_destroy (icon=0x1bdcfe0) at ../wlroots-0.15.1/types/data_device/wlr_drag.c:361
#14 drag_destroy (drag=0x19b66a0) at ../wlroots-0.15.1/types/data_device/wlr_drag.c:159
#15 0x00007f1d5fac88fe in wlr_signal_emit_safe (signal=<optimized out>, data=0x1ba7210) at ../wlroots-0.15.1/util/signal.c:29
        pos = 0x19b6770
        l = 0x19b6770
        cursor = {link = {prev = 0x1ba7240, next = 0x18c3110}, notify = 0x7f1d5fac5f10 <handle_noop>}
        end = {link = {prev = 0x18c3110, next = 0x1ba7240}, notify = 0x7f1d5fac5f10 <handle_noop>}
#16 0x00007f1d5fa91ccf in wlr_data_source_destroy (source=0x1ba7210) at ../wlroots-0.15.1/types/data_device/wlr_data_source.c:42
        p = <optimized out>
#17 wlr_data_source_destroy (source=0x1ba7210) at ../wlroots-0.15.1/types/data_device/wlr_data_source.c:37
#18 0x00007f1d5fa945f9 in drag_handle_pointer_button
    (grab=0x19b66c0, time=<optimized out>, button=<optimized out>, state=<optimized out>)
    at ../wlroots-0.15.1/types/data_device/wlr_drag.c:226
        drag = <optimized out>
#19 0x000000000024f407 in Cursor.handleButton (listener=<optimized out>, event=0x7ffe9473fdc0) at Cursor.zig:294
        self = 0x1887f28
        result =
            {surface = <optimized out>, sx = <optimized out>, sy = <optimized out>, parent = {payload = {view = <optimized out>, layer_surface = <optimized out>}, tag = <optimized out>}}
        wlr_output = <optimized out>
#20 .wayland.wayland_server_core.struct:490:17.wrapper (listener=<optimized out>, data=0x7ffe9473fdc0)
    at /home/jens/aur/river/src/river-0.1.3/zig-cache/zig-wayland/wayland_server_core.zig:492
#21 0x00007f1d5fac88fe in wlr_signal_emit_safe (signal=<optimized out>, data=0x7ffe9473fdc0) at ../wlroots-0.15.1/util/signal.c:29
        pos = 0x1887fb8
        l = 0x1887fb8
        cursor = {link = {prev = 0x1887fb8, next = 0x7ffe9473fca0}, notify = 0x7f1d5fac5f10 <handle_noop>}
        end = {link = {prev = 0x7ffe9473fcc0, next = 0x18c3308}, notify = 0x7f1d5fac5f10 <handle_noop>}
#22 0x00007f1d5fac88fe in wlr_signal_emit_safe (signal=<optimized out>, data=0x7ffe9473fdc0) at ../wlroots-0.15.1/util/signal.c:29
        pos = 0x1c15880
        l = 0x1c15880
        cursor = {link = {prev = 0x1c15880, next = 0x7ffe9473fd10}, notify = 0x7f1d5fac5f10 <handle_noop>}
        end = {link = {prev = 0x7ffe9473fd30, next = 0x1c15758}, notify = 0x7f1d5fac5f10 <handle_noop>}
#23 0x00007f1d5fa86edd in handle_pointer_button (libinput_dev=<optimized out>, event=0x19b6600)
    at ../wlroots-0.15.1/backend/libinput/pointer.c:88
        wlr_dev = 0x1c156b0
        pevent = 0x19b6600
--Type <RET> for more, q to quit, c to continue without paging--
        wlr_event = {device = 0x1c156b0, time_msec = 125750160, button = 272, state = WLR_BUTTON_RELEASED}
        libinput_dev = <optimized out>
        event_type = <optimized out>
        event = 0x19b6600
        backend = <optimized out>
        ret = <optimized out>
#24 handle_libinput_event (event=0x19b6600, backend=0x1239c70) at ../wlroots-0.15.1/backend/libinput/events.c:257
        libinput_dev = <optimized out>
        event_type = <optimized out>
        event = 0x19b6600
        backend = <optimized out>
        ret = <optimized out>
#25 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>)
    at ../wlroots-0.15.1/backend/libinput/backend.c:58
        event = 0x19b6600
        backend = <optimized out>
        ret = <optimized out>
#26 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>)
    at ../wlroots-0.15.1/backend/libinput/backend.c:48
        backend = <optimized out>
        ret = <optimized out>
#27 0x00007f1d5fc111ca in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#28 0x00007f1d5fc0ed37 in wl_display_run () at /lib64/libwayland-server.so.0
#29 0x000000000022a713 in main () at main.zig:126
        cmd = {ptr = <optimized out>, len = <optimized out>}
        child_pgid = {val = 67325, maybe = true}
        pgid = <optimized out>
        result =
                {args = {ptr = 0x7ffe94740570, len = 0}, flag_data = {{name = 0x20935f <anon.217c524444570a17a39c95cbf69bd115> "-h", value = {payload = {boolean = false, arg = 0x0}, tag = boolean}}, {name = 0x20922e <anon.217c524444570a17a39c95cbf69bd115> "-version", value = {payload = {boolean = false, arg = 0x0}, tag = boolean}}, {name = 0x209749 <anon.217c524444570a17a39c95cbf69bd115> "-c", value = {payload = {boolean = false, arg = 0x0}, tag = arg}}, {name = 0x2092c3 <anon.217c524444570a17a39c95cbf69bd115> "-log-level", value = {payload = {boolean = false, arg = 0x0}, tag = arg}}}}
        argv = {ptr = <optimized out>, len = <optimized out>}
        level = {ptr = <optimized out>, len = <optimized out>}
        startup_command = {val = {ptr = 0x1237eb0 "", len = <synthetic pointer>}, maybe = <synthetic pointer>}
        err = <optimized out>
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#30 std.start.callMain () at /usr/lib/zig/std/start.zig:553
        err = <optimized out>
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#31 std.start.initEventLoopAndCallMain () at /usr/lib/zig/std/start.zig:495
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#32 std.start.callMainWithArgs (argc=<optimized out>, argv=<optimized out>, envp=...) at /usr/lib/zig/std/start.zig:445
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#33 std.start.main (c_argc=<optimized out>, c_argv=<optimized out>, c_envp=<optimized out>) at /usr/lib/zig/std/start.zig:460
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}`
This happens occasionally when I (involuntarily) click&drag som UI element in Chrome (eg. a picture or large selection of text), and release the mouse button. I can't reproduce at will, but it's crashed in the same way three times now in as many days, so it's not an isolated incident. I should probably mention that I use touch input patches from https://github.com/riverwm/river/pull/477 - however this crash was triggered with an external mouse.

**Comment by ifreund** [comment]
What river version are you running?

**Comment by regenman** [comment]
I'm running river version 0.1.3.
```
$ pacman -Qs "^(river|wlroots|zig|wayland)$" | grep local
local/river 0.1.3-1
local/wayland 1.20.0-1
local/wlroots 0.15.1-2
local/zig 0.9.0-1
```
