### ISSUE TITLE
river freezes completely when switching tag away from pcmanfm

### ISSUE THREAD

**Issue by tleydxdy** [riverwm/river#734]
I found that pcmanfm (the gtk2 version) will reliably freezes river after the recent update (I haven't used it before that so not sure if it's an preexisting problem). step to reproduce is simple

1. arch system, get pcmanfm (not pcmanfm-gtk3) and river on master branch
2. sleep 10; pkill -9 river
3. open pcmanfm
4. select an different tag so pcmanfm go out of view
5. the whole display freezes after a split second
6. river gets killed and drop back to vt

logs for the above step are as follow
[river-err.log](https://github.com/riverwm/river/files/10200980/river-err.log)
xwayland crashing seems to cause the freeze, here's the coredump
```
Core was generated by `Xwayland :0 -rootless -core -terminate -listenfd 25 -listenfd 26 -displayfd 32'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading 0.00 MB source file /usr/src/debug/glibc/nptl/pthread_kill.c
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                                                                      
[Current thread is 1 (Thread 0x7f5579bb08c0 (LWP 25378))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f557a4d26b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f557a482958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f557a46c53d in __GI_abort () at abort.c:79
#4  0x0000561eb4554241 in ?? ()
#5  0x0000561eb455de7d in ?? ()
#6  0x0000561eb4420441 in ?? ()
#7  0x00007f557a99445a in wl_log (fmt=fmt@entry=0x7f557a99a310 "[destroyed object]: error %d: %s\n") at ../wayland-1.21.0/src/wayland-util.c:449
#8  0x00007f557a994a6b in display_handle_error (data=<optimized out>, display=0x561eb4fb7270, object=0x0, code=4294967295, message=<optimized out>)
    at ../wayland-1.21.0/src/wayland-client.c:1024
#9  0x00007f557a3534f6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#10 0x00007f557a34ff5e in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>)
    at ../src/x86/ffi64.c:673
#11 0x00007f557a352b73 in ffi_call (cif=cif@entry=0x7ffc9174af30, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffc9174b000) at ../src/x86/ffi64.c:710
#12 0x00007f557a995645 in wl_closure_invoke (closure=closure@entry=0x561eb5bb8fd0, target=<optimized out>, target@entry=0x561eb4fb7270, opcode=opcode@entry=0, 
    data=<optimized out>, flags=1) at ../wayland-1.21.0/src/connection.c:1025
#13 0x00007f557a995e03 in dispatch_event (display=display@entry=0x561eb4fb7270, queue=0x561eb4fb7328) at ../wayland-1.21.0/src/wayland-client.c:1595
#14 0x00007f557a995fcf in dispatch_queue (queue=0x561eb4fb7340, display=0x561eb4fb7270) at ../wayland-1.21.0/src/wayland-client.c:1734
#15 wl_display_dispatch_queue_pending (display=0x561eb4fb7270, queue=0x561eb4fb7340) at ../wayland-1.21.0/src/wayland-client.c:1983
#16 0x0000561eb4427d7d in ?? ()
#17 0x0000561eb45536b2 in ?? ()
#18 0x0000561eb44912f9 in ?? ()
#19 0x0000561eb441e1fe in ?? ()
#20 0x00007f557a46d290 in __libc_start_call_main (main=main@entry=0x561eb441ca20, argc=argc@entry=13, argv=argv@entry=0x7ffc9174c0d8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#21 0x00007f557a46d34a in __libc_start_main_impl (main=0x561eb441ca20, argc=13, argv=0x7ffc9174c0d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffc9174c0c8) at ../csu/libc-start.c:381
#22 0x0000561eb441fa95 in ?? ()
```

**Comment by tleydxdy** [comment]
that one I just got from arch and the version is 22.1.5

**Comment by tleydxdy** [comment]
got another crash, this time inside river
```
(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {12297829382473034410}}
        ret = <optimized out>
#1  0x00007fd4690296b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fd468fd9958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007fd468fc353d in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {140550272024836, 0, 1, 2148319, 1, 20, 2205022, 2189192, 0, 140730556300824, 140730556300816, 140730556301360, 2202282, 1, 0, 2148319}}, sa_flags = 1, sa_restorer = 0xd0b10770c355d00}
#4  0x000000000021ae86 in std.os.abort () at /usr/lib/zig/std/os.zig:443
#5  0x0000000000261d97 in std.debug.handleSegfaultPosix (sig=11, info=0x7ffe62d14170, ctx_ptr=0x7ffe62d14040) at /usr/lib/zig/std/debug.zig:1741
        addr = <optimized out>
#6  0x00007fd468fd9a00 in <signal handler called> () at /lib64/libc.so.6
#7  0x00007fd469201e7b in wl_signal_add (listener=<optimized out>, signal=<optimized out>) at /usr/include/wayland-server-core.h:447
        toplevel_output = 0x269fc40
#8  wlr_foreign_toplevel_handle_v1_output_enter (toplevel=0x2461520, output=0x60) at ../wlroots-0.16.0/types/wlr_foreign_toplevel_management_v1.c:306
        toplevel_output = 0x269fc40
#9  0x000000000025dd36 in View.map (self=0x2945b50) at View.zig:496
        handle = 0x2461520
        s = <optimized out>
        s = <optimized out>
        node = <optimized out>
        it = <optimized out>
        seat_node = <optimized out>
#10 0x000000000025da06 in XwaylandView.handleMap (listener=<optimized out>, xwayland_surface=<optimized out>) at XwaylandView.zig:237
        self = <optimized out>
        surface = 0x2961c00
        size_hints = <optimized out>
        view = 0x2945b50
        has_fixed_size = <optimized out>
#11 .wayland.wayland_server_core.struct:490:17.wrapper (listener=<optimized out>, data=<optimized out>) at /home/tleydxdy/software/river/zig-cache/zig-wayland/wayland_server_core.zig:492
#12 0x00007fd46938af6e in wl_signal_emit_mutable (signal=signal@entry=0x2928dd8, data=data@entry=0x2928c50) at ../wayland-1.21.0/src/wayland-server.c:2179
        pos = 0x2945b80
        l = 0x2945b80
        cursor = {link = {prev = 0x2945b80, next = 0x7ffe62d148d0}, notify = 0x7fd469388110 <handle_noop>}
        end = {link = {prev = 0x7ffe62d148f0, next = 0x2928dd8}, notify = 0x7fd469388110 <handle_noop>}
#13 0x00007fd469223792 in xwayland_surface_role_commit (wlr_surface=<optimized out>) at ../wlroots-0.16.0/xwayland/xwm.c:830
        surface = 0x2928c50
        __PRETTY_FUNCTION__ = "xwayland_surface_role_commit"
#14 0x00007fd4691facad in surface_commit_state (surface=0x2961c00, next=0x2961d88) at ../wlroots-0.16.0/types/wlr_compositor.c:496
        invalid_buffer = <optimized out>
        subsurface = 0x2961df0
        __PRETTY_FUNCTION__ = "surface_commit_state"
#15 0x00007fd468e474f6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#16 0x00007fd468e43f5e in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:673
        classes = {X86_64_INTEGER_CLASS, 32766, 1759782588, 32724}
        stack = <optimized out>
        argp = 0x7ffe62d149d0 ""
        arg_types = <optimized out>
        gprcount = 2
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        flags = <optimized out>
        reg_args = <optimized out>
#17 0x00007fd468e46b73 in ffi_call (cif=cif@entry=0x7ffe62d14b80, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffe62d14c50) at ../src/x86/ffi64.c:710
        arg_types = 0x7ffe62d14ba0
        i = <optimized out>
        nargs = 2
        max_reg_struct_size = <optimized out>
#18 0x00007fd469389ada in wl_closure_invoke (closure=closure@entry=0x2960dc0, target=<optimized out>, target@entry=0x247b190, opcode=opcode@entry=6, data=<optimized out>, data@entry=0x228dd40, flags=2) at ../wayland-1.21.0/src/connection.c:1025
        count = <optimized out>
        cif = {abi = FFI_UNIX64, nargs = 2, arg_types = 0x7ffe62d14ba0, rtype = 0x7fd468e481a0 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = {0x7fd468e482a0 <ffi_type_pointer>, 0x7fd468e482a0 <ffi_type_pointer>, 0x7fd468e48330 <ffi_type_sint32>, 0x7fd468e48330 <ffi_type_sint32>, 0x7fd468e48330 <ffi_type_sint32>, 0x7fd468e48330 <ffi_type_sint32>, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b35230, 0xd0b10770c355d00, 0x1b35230, 0x7ffe62d14c80, 0x0, 0x259c3c <.wayland.wayland_server_core.struct:490:17.wrapper+2012>}
        ffi_args = {0x7ffe62d14b60, 0x7ffe62d14b68, 0x296f198, 0x296f1a0, 0x296f1a8, 0x296f1b0, 0xf, 0x2d85e793, 0x0, 0x7fd46938b471 <log_closure+81>, 0x29a6eb0, 0x1932ee0, 0x7fd469179ba0 <main_arena>, 0x0, 0x296f180, 0x7fd469038416 <__libc_calloc+214>, 0x7ffe62d14d20, 0xd0b10770c355d00, 0x28d3960, 0x7fd46939042d, 0x7fd469395470 <wl_surface_requests+144>, 0x0}
        implementation = <optimized out>
#19 0x00007fd46938e01c in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wayland-1.21.0/src/wayland-server.c:437
        client = <optimized out>
        connection = <optimized out>
        resource = 0x247b190
        object = 0x247b190
        closure = 0x2960dc0
        message = 0x7fd469395470 <wl_surface_requests+144>
        p = {267, 524294}
        resource_flags = 0
        opcode = 6
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#20 0x00007fd46938c9e2 in wl_event_loop_dispatch (loop=0x1932fd0, timeout=timeout@entry=-1) at ../wayland-1.21.0/src/event-loop.c:1027
        ep = {{events = 1, data = {ptr = 0x2294150, fd = 36258128, u32 = 36258128, u64 = 36258128}}, {events = 1, data = {ptr = 0x2481130, fd = 38277424, u32 = 38277424, u64 = 38277424}}, {events = 204823808, data = {ptr = 0xd0b1077, fd = 218828919, u32 = 218828919, u64 = 218828919}}, {events = 1, data = {ptr = 0x18, fd = 24, u32 = 24, u64 = 24}}, {events = 38216720, data = {ptr = 0x62d14fd000000000, fd = 0, u32 = 0, u64 = 7120560240621256704}}, {events = 32766, data = {ptr = 0x2475428, fd = 38229032, u32 = 38229032, u64 = 38229032}}, {events = 38220824, data = {ptr = 0x62d1501000000000, fd = 0, u32 = 0, u64 = 7120560515499163648}}, {events = 32766, data = {ptr = 0x7fd469389500 <wl_connection_flush+304>, fd = 1765315840, u32 = 1765315840, u64 = 140550275110144}}, {events = 1, data = {ptr = 0x180247fe10, fd = 38272528, u32 = 38272528, u64 = 103117487632}}, {events = 0, data = {ptr = 0x7ffe62d15030, fd = 1657884720, u32 = 1657884720, u64 = 140730556305456}}, {events = 6, data = {ptr = 0x253c00 <.wayland.wayland_server_core.struct:490:17.wrapper+640>, fd = 2440192, u32 = 2440192, u64 = 2440192}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1657884688, data = {ptr = 0x100007ffe, fd = 32766, u32 = 32766, u64 = 4295000062}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7fd469073513 <__libc_fork+531>, fd = 1762080019, u32 = 1762080019, u64 = 140550271874323}}, {events = 38223896, data = {ptr = 0x1800000000, fd = 0, u32 = 0, u64 = 103079215104}}, {events = 0, data = {ptr = 0x2473418, fd = 38220824, u32 = 38220824, u64 = 38220824}}, {events = 8, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 127, data = {ptr = 0x68fc33e000000080, fd = 128, u32 = 128, u64 = 7564978511241281664}}, {events = 32724, data = {ptr = 0x7fd469179ba0 <main_arena>, fd = 1763154848, u32 = 1763154848, u64 = 140550272949152}}, {events = 1763161904, data = {ptr = 0x62d1512000007fd4, fd = 32724, u32 = 32724, u64 = 7120561683730300884}}, {events = 32766, data = {ptr = 0x7fd469098104 <__GI___libc_write+100>, fd = 1762230532, u32 = 1762230532, u64 = 140550272024836}}, {events = 1657884816, data = {ptr = 0x1500007ffe, fd = 32766, u32 = 32766, u64 = 90194345982}}, {events = 0, data = {ptr = 0x20cf56 <anon.217c524444570a17a39c95cbf69bd115>, fd = 2150230, u32 = 2150230, u64 = 2150230}}, {events = 21, data = {ptr = 0x5053494400000000, fd = 0, u32 = 0, u64 = 5788050502507823104}}, {events = 1029259596, data = {ptr = 0x21a55e <std.fs.file.File.write+62>, fd = 2205022, u32 = 2205022, u64 = 2205022}}, {events = 2185320, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7ffe62d151f0, fd = 1657885168, u32 = 1657885168, u64 = 140730556305904}}, {events = 204823808, data = {ptr = 0x7b90d0b1077, fd = 218828919, u32 = 218828919, u64 = 8491369173111}}, {events = 0, data = {ptr = 0x2461c00, fd = 38149120, u32 = 38149120, u64 = 38149120}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
#21 0x00007fd46938d197 in wl_display_run (display=0x1932ee0) at ../wayland-1.21.0/src/wayland-server.c:1431
#22 0x000000000022bc91 in main () at main.zig:135
        cmd = {ptr = <optimized out>, len = <optimized out>}
        child_pgid = {val = 1977, maybe = true}
        pgid = <optimized out>
        result = {args = {ptr = 0x7ffe62d15600, len = 0}, flag_data = {{name = 0x209a63 <anon.217c524444570a17a39c95cbf69bd115> "-h", value = {payload = {boolean = false, arg = 0x0}, tag = boolean}}, {name = 0x2097ef <anon.217c524444570a17a39c95cbf69bd115> "-version", value = {payload = {boolean = false, arg = 0x0}, tag = boolean}}, {name = 0x20a3da <anon.217c524444570a17a39c95cbf69bd115> "-c", value = {payload = {boolean = false, arg = 0x0}, tag = arg}}, {name = 0x209935 <anon.217c524444570a17a39c95cbf69bd115> "-log-level", value = {payload = {boolean = false, arg = 0x7ffe62d176c2 "debug"}, tag = arg}}}}
        argv = {ptr = <optimized out>, len = <optimized out>}
        level = {ptr = <optimized out>, len = <optimized out>}
        startup_command = {val = {ptr = 0x1932eb0 "", len = <synthetic pointer>}, maybe = <synthetic pointer>}
        err = <optimized out>
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#23 std.start.callMain () at /usr/lib/zig/std/start.zig:561
        err = <optimized out>
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#24 std.start.initEventLoopAndCallMain () at /usr/lib/zig/std/start.zig:495
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#25 std.start.callMainWithArgs (argc=<optimized out>, argv=<optimized out>, envp=...) at /usr/lib/zig/std/start.zig:445
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
#26 std.start.main (c_argc=<optimized out>, c_argv=<optimized out>, c_envp=<optimized out>) at /usr/lib/zig/std/start.zig:460
        env_count = <optimized out>
        envp = {ptr = <optimized out>, len = <optimized out>}
```

**Comment by novakne** [comment]
Seems like there is this bug with gtk2 in sway too https://github.com/swaywm/sway/issues/7139

**Comment by tleydxdy** [comment]
Seems like this issue is solved, probably by https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/f1bea43ccccd5824097d8660a2d20b5d0bf506be opening pcmanfm and switching tag no longer freezes river

**Comment by ifreund** [comment]
Excellent, that does indeed seem likely to be the fix. Thanks for confirming!
