### ISSUE TITLE
session-lock: crash when waking up from sleep in a laptop+monitor setup

### ISSUE THREAD

**Issue by MaxVerevkin** [riverwm/river#781]
### How to reproduce

1. Setup: laptop with disabled monitor and an enabled external monitor. `swayidle` is configured to run a custom session-lock client.
2. Close laptop's lid to suspend.
3. Press a key an a keyboard to wake up.
4. River panics.

### River log

```
info(wlroots): [backend/drm/drm.c:586] connector HDMI-A-1: Modesetting with 1920x1080 @ 60.000 Hz
thread 484346 panic: reached unreachable code
/usr/lib/zig/std/debug.zig:278:14: 0x24f896 in assert (river)
    if (!ok) unreachable; // assertion failure
             ^
/home/maxv/river/river/Output.zig:545:48: 0x25403f in wrapper (river)
        .unlocked => assert(server.lock_manager.state != .locked),
                                               ^
???:?:?: 0x7fab07accf6d in ??? (???)
```

### Backtrace

```
(gdb) bt full
#0  0x00007fab0776c64c in  () at /lib64/libc.so.6
#1  0x00007fab0771c938 in raise () at /lib64/libc.so.6
#2  0x00007fab0770653d in abort () at /lib64/libc.so.6
#3  0x00000000002a4fe9 in os.abort () at /usr/lib/zig/std/os.zig:560
#4  0x0000000000261728 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /usr/lib/zig/std/debug.zig:384
#5  0x000000000024d50a in builtin.default_panic (msg=..., error_return_trace=0x0, ret_addr=...) at /usr/lib/zig/std/builtin.zig:839
        first_trace_addr = 2422935
#6  0x000000000024f897 in debug.assert (ok=false) at /usr/lib/zig/std/debug.zig:278
#7  0x0000000000254040 in Output.handlePresent () at Output.zig:545
        self = 0x20b38d0
        listener = 0x20b3a48
        event = 0x7fffd3328620
#8  wayland_server_core.Listener(*types.output.Output.event.Present).setNotify__struct_11841.wrapper (listener=0x20b3a48, data=0x7fffd3328620)
    at /home/maxv/river/zig-cache/zig-wayland/wayland_server_core.zig:520
#9  0x00007fab07accf6e in wl_signal_emit_mutable () at /lib64/libwayland-server.so.0
#10 0x00007fab0792b95f in wlr_output_send_present () at /lib64/libwlroots.so.11
#11 0x00007fab079112eb in  () at /lib64/libwlroots.so.11
#12 0x00007fab0757d7cf in drmHandleEvent () at /usr/lib/libdrm.so.2
#13 0x00007fab0791028e in  () at /lib64/libwlroots.so.11
#14 0x00007fab07ace9e2 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#15 0x00007fab07acf197 in wl_display_run () at /lib64/libwayland-server.so.0
#16 0x000000000025f57c in main.main () at main.zig:132
        startup_command = {ptr = 0x15bfeb0 "\360\220\364\001", len = 29}
        result = {args = {ptr = 0x7fffd3329450, len = 0}, flags = {h = false, version = false, c = {ptr = 0x0, len = 0}, log-level = {ptr = 0x7fffd332ab14 "debug", len = 5}}}
        child_pgid = {data = 484385, some = 1 '\001'}
```

**Comment by ifreund** [comment]
Could you share the full river log?

**Comment by MaxVerevkin** [comment]
http://ix.io/4m6F

**Comment by ifreund** [comment]
I think this should fix it, would you mind testing?
```diff
diff --git a/river/Output.zig b/river/Output.zig
index 2e22524..bacebe5 100644
--- a/river/Output.zig
+++ b/river/Output.zig
@@ -82,7 +82,7 @@ lock_render_state: enum {
     pending_lock_surface,
     /// The lock surface buffer has been presented.
     lock_surface,
-} = .unlocked,
+} = .blanked,
 
 /// The double-buffered state of the output.
 current: State = State{ .tags = 1 << 0 },
```
I want to think a bit more carefully about whether this is correct in all cases before I push it to master though.

**Comment by MaxVerevkin** [comment]
Fixes for me

**Comment by ifreund** [comment]
Thanks for trying it out. Just pushed 76952183c0cde7a8e2c53173567f9f98ae5258c6 to master.
