### ISSUE TITLE
Crash when running `riverctl default-layout <anything>`

### ISSUE THREAD

**Issue by MaxVerevkin** [riverwm/river#848]
River panics when trying to switch the default layout while previous layout is still running.

Backtrace:

```
#0  0x00007f7089abc26c in  () at /lib64/libc.so.6
#1  0x00007f7089a6ca08 in raise () at /lib64/libc.so.6
#2  0x00007f7089a55538 in abort () at /lib64/libc.so.6
#3  0x00000000002a7169 in os.abort () at /usr/lib/zig/std/os.zig:560
#4  0x0000000000262c08 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /usr/lib/zig/std/debug.zig:384
#5  0x000000000024edaa in builtin.default_panic (msg=..., error_return_trace=0x0, ret_addr=...) at /usr/lib/zig/std/builtin.zig:839
        first_trace_addr = 2429239
#6  0x0000000000251137 in debug.assert (ok=false) at /usr/lib/zig/std/debug.zig:278
#7  0x00000000002e33d2 in LayoutDemand.apply (self=0x18617e8, layout=0x1617450) at LayoutDemand.zig:155
#8  0x00000000002ba419 in Layout.handleRequest (layout=0x18a3280, request=..., self=0x1617450) at Layout.zig:159
        new_name = {ptr = 0x7f7089c7f64f <wlr_output_send_present+79> "H\213D$\030dH+\004%(", len = 0}
#9  0x00000000002bab67 in common.Dispatcher(river_layout_v3_server.LayoutV3,*Layout).dispatcher (implementation=0x2ba0b0 <Layout.handleRequest>, object=0x18a3280, opcode=2, args=0x160c298)
    at /home/maxv/river/zig-cache/zig-wayland/common.zig:107
        payload_data = {layout_name = 0x160c35c "rivertile-simple", serial = 21}
#10 0x00007f7089e22023 in  () at /lib64/libwayland-server.so.0
#11 0x00007f7089e20ae2 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#12 0x00007f7089e212d7 in wl_display_run () at /lib64/libwayland-server.so.0
#13 0x00000000002609cc in main.main () at main.zig:132
        startup_command = {ptr = 0xc742e0 "p\002`\001", len = 29}
        result = {args = {ptr = 0x7fff996292f0, len = 0}, flags = {h = false, version = false, c = {ptr = 0x0, len = 0}, log-level = {ptr = 0x7fff9962aaea "debug", len = 5}}}
        child_pgid = {data = 198333, some = 1 '\001'}
```

[Log](https://paste.rs/Us36I)

**Comment by ifreund** [comment]
Should be fixed by 470eb222803a6382fd444e133b675fcc168fbf60, thanks for the report and stack trace!
